name: Build Hoprnet

on:
  push:
    branches:
      - latest
      - feat/*
      - fix/*
      - ausias/*
  workflow_dispatch:
jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@ac3e0b6137b0ba470a30c373aab2ceba9e0879e4
        with:
          workload_identity_provider: ${{ vars.HOPRNET_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.HOPRNET_SERVICE_ACCOUNT }}
          login_artifact_registry: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # 4.1.0
      - name: Build and push frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # 7.2.0
        with:
          context: keep-ui
          file: docker/Dockerfile.ui
          push: true
          tags: ${{ vars.HOPRNET_REGISTRY }}/keep-ui:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            KEEP_DEBUG=true

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - name: Setup GCP
        uses: hoprnet/hopr-workflows/actions/setup-gcp@ac3e0b6137b0ba470a30c373aab2ceba9e0879e4
        with:
          workload_identity_provider: ${{ vars.HOPRNET_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.HOPRNET_SERVICE_ACCOUNT }}
          login_artifact_registry: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # 4.1.0
      - name: Build and push frontend image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # 7.2.0
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: ${{ vars.HOPRNET_REGISTRY }}/keep-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max